### ISSUE TITLE
The app contains or inherits from non-public classes in Payload/PBPopupSample.app/PBPopupSample: CAFilter

### ISSUE THREAD

**Issue by balabon7** [jtrivedi/VariableBlurView#1]
Hello 👋

When I tried to upload a build that used VariableBlurUIView to the AppStore, an error occurred.

If you've published your app, perhaps you've found a workaround?

<img width="769" alt="Знімок екрана 2023-07-14 о 02 26 42" src="https://github.com/jtrivedi/VariableBlurView/assets/42384032/48e4d5e2-fd1a-48f5-b601-ba6991822140">

**Comment by balabon7** [comment]
Sorry to bother you, I found a solution

**Comment by inb4ohnoes** [comment]
> Sorry to bother you, I found a solution

What was the solution?
