### ISSUE TITLE
Thanks for this! :) Currently not working though...?

### ISSUE THREAD

**Issue by qusc** [jtrivedi/VariableBlurView#2]
<img width="559" alt="Screenshot 2023-10-13 at 11 29 53" src="https://github.com/jtrivedi/VariableBlurView/assets/27284448/0e93eb1d-10be-4dd9-8a9a-1b9ac16a02c0">

This is not what it's supposed to look like right?

**Comment by qusc** [comment]
Nevermind for some reason it just breaks temporarily when switching light / dark mode which I did right on startup

**Comment by Saturn-V** [comment]
I do manage to reproduce this when switching apps as well. happens every time. is it just me? am looking into my code to see what else could be the culprit
